### ISSUE TITLE
ValueError: x and y must have same first dimension, but have shapes (1,) and (306,)

### ISSUE THREAD

**Issue by lategoodbye** [t2y/iostat-tool#4]
Hi,
i try to use iostat-cli (version 0.3.0) but i only get this stacktrace:

iostat-cli --data 5.19_SDCIT_patch_nooptimize_download_success.iostat.log --disk mmcblk1 --fig-output success.png plot
Traceback (most recent call last):
  File "/home/beep/.local/bin/iostat-cli", line 8, in <module>
    sys.exit(main())
  File "/home/beep/.local/lib/python3.10/site-packages/iostat/main.py", line 217, in main
    plotter.plot()
  File "/home/beep/.local/lib/python3.10/site-packages/iostat/plotter.py", line 202, in plot
    self.plot_device(datetime_data)
  File "/home/beep/.local/lib/python3.10/site-packages/iostat/plotter.py", line 188, in plot_device
    self.subplots[name].plot(x, values, label=column)
  File "/home/beep/.local/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 1635, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/home/beep/.local/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 312, in __call__
    yield from self._plot_args(this, kwargs)
  File "/home/beep/.local/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 498, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (1,) and (306,)

What's wrong here?
Thanks in advance

[5.19_SDCIT_patch_nooptimize_download_success.iostat.log](https://github.com/t2y/iostat-tool/files/9421890/5.19_SDCIT_patch_nooptimize_download_success.iostat.log)

**Comment by Bschitter** [comment]
I am also getting the same or a very similar error:

```shell
iostat-cli --data iostat.log --disk sdc --fig-output sdc.png plot --without-cpu
Traceback (most recent call last):
  File "/home/bschitter/.local/bin/iostat-cli", line 8, in <module>
    sys.exit(main())
  File "/home/bschitter/.local/lib/python3.10/site-packages/iostat/main.py", line 217, in main
    plotter.plot()
  File "/home/bschitter/.local/lib/python3.10/site-packages/iostat/plotter.py", line 202, in plot
    self.plot_device(datetime_data)
  File "/home/bschitter/.local/lib/python3.10/site-packages/iostat/plotter.py", line 188, in plot_device
    self.subplots[name].plot(x, values, label=column)
  File "/home/bschitter/.local/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 1668, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/home/bschitter/.local/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 311, in __call__
    yield from self._plot_args(
  File "/home/bschitter/.local/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 504, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (1,) and (15012,)
```

Python Version: Python 3.10.6
OS: Linux Mint 21.1

**Comment by Bschitter** [comment]
I figured out, that my iostat log file had an unsupported date format.
After changing it from `%d.%m.%Y %H:%M:%S` to `%m/%d/%Y %I:%M:%S %p` all worked fine.

@lategoodbye maybe that is also the problem in your case

**Comment by lyh543** [comment]
After running export `LC_ALL=en_US.UTF-8`, my iostat result works well.

Can you please raise a more friendly error message when the date format is error.
